image: node:22

stages:
  - publish

publish:
  stage: publish
  tags:
    - docker
  only:
    - tags
  script:
    # create .npmrc pointing @q1 to your GitLab registry
    - |
      cat > .npmrc <<EOF
      @q1:registry=https://git.zahlz.com/api/v4/projects/454/packages/npm/
      //git.zahlz.com/api/v4/projects/454/packages/npm/:_authToken=${CI_JOB_TOKEN}
      EOF
    # install dependencies
    - npm ci
    # compile typescript
    - npx tsc
    # set package name
    - npm pkg set name=@q1/eslint-plugin-jk-2
    # publish to GitLab registry
    - npm publish
